# SSL Bootstrap Compose
# Used only during initial certificate generation
# Usage: docker compose -f docker-compose.acme.yml up -d

services:
  nginx:
    image: nginx:alpine@sha256:df221db836e1754089190208cee7eeda94f233197056426eda74a43ab1abeac2
    container_name: tft-nginx-acme
    ports:
      - "80:80"
    volumes:
      - ./deployment/nginx/acme.conf:/etc/nginx/nginx.conf:ro
      - ./deployment/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot@sha256:f70ad0adbb7e117f0fe42a63c553f28ea451edabc0148757b6efcd9735acaa20
    container_name: tft-certbot
    volumes:
      - ./deployment/certbot/conf:/etc/letsencrypt
      - ./deployment/certbot/www:/var/www/certbot
